services:
  db:
    image: mysql:8.4
    container_name: meu-mysql
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-senai}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-autoescola}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-senai}

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - app-network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD:-senai}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: meu-rabbit
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: auto-escola-n116
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-senai}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-autoescola}

      JWT_SECRET: ${JWT_SECRET:-12345678}

      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      E_MAIL: ${E_MAIL}
      SENHA_APP: ${SENHA_APP}

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge