server.port=8080
spring.datasource.url=${MYSQL_UR}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

api.security.token.secret=${JWT_SECRET}
app.cors.allowed-origins=\
"http://localhost:3000"\
"http://www.meuapp.com.br/fe"
app.security.allowed-origins=http://localhost:8080

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${E_MAIL:cemoliveir@gmail.com}
spring.mail.password=${SENHA_APP:kvdg zfvg fire gqqy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.conectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000