CREATE TABLE USUARIOS
(
    id     BIGINT       NOT NULL AUTO_INCREMENT,
    login  VARCHAR(100) NOT NULL UNIQUE,
    senha  VARCHAR(255) NOT NULL,
    ativo  TINYINT      NOT NULL DEFAULT 1,
    perfil VARCHAR(10)  NOT NULL,

    PRIMARY KEY (id)
);